### ISSUE TITLE
Failed to load sap/m.js

### ISSUE THREAD

**Issue by leonardstock** [mauriciolauffer/openui5-tour#11]
Hi,
we would love to use the tour control, but unfortunately I am getting the error described in the title. Comparing with your demo, I saw that the same error occured for it too! I included the dist/resources/openui5/tour exactly as specified in the readme but please let me know if there is anything I did incorrectly.

__manifest.json:__
```
"sap.ui5": {
        "_version": "1.1.0",
        "autoPrefixId": true,
       [...]
        "dependencies": {
            "minUI5Version": "1.58.0",
            "libs": {
                "sap.ui.core": {},
                "sap.m": {},
                "sap.ui.layout": {},
                "openui5.tour": {}
            },
          [...]
        },
        "models": [...],
        "resources": [...],
        "resourceRoots": {
            "openui5.tour": "lib/openui5/tour/"
        },
       [...]
        }
    }
```

**Comment by DusanSacha** [comment]
Hi @leonardstock,
were you able to solve the issue on your local? I would like to use this project as well...

**Comment by leonardstock** [comment]
Hi @DusanSacha,
I haven't looked into it any further, sorry! I thought it might be easier for @mauriciolauffer to look into as it might be a config issue.

**Comment by mauriciolauffer** [comment]
Hi @leonardstock and @DusanSacha. Sorry for the delay.

It was an issue on loading sap.m library. I've just fixed it and published a new version.
https://www.npmjs.com/package/openui5-tour/v/0.0.27

Demo is working fine now:
https://mauriciolauffer.github.io/openui5-tour/demo/webapp/index.html
